version: '3.5'

services:
  bot:
    image: docker.antti.codes/iiow/iislander
    env_file:
      - .env
    volumes:
      - data:/app/data
      - backups:/app/backups
    restart: on-failure:5
    stop_grace_period: 10s

volumes:
  data:
