/**
 * The passed words are seperated by new line and are Regex, + means the char before one or more times
 */
export default {
    swearwords: [
        'ar+s+e',
        'anal',
        'anus',
        'boo+b',
        'bitch',
        'ball(bag|sack)',
        'bastard',
        'blowjob',
        'boner',
        'butt(hole|plug)',
        '(c|k)ock',
        'clit',
        'cunt',
        'cum',
        'condom',
        'dick',
        'dildo',
        'dyke',
        'ejaculate',
        '(f|ph)(u|o)+(c?k|q|x)',
        'fag',
        'gangbang',
        'horn(y|i)',
        'jackoff',
        'jerkoff',
        'mof(o|u)',
        'mast(u|e)rb(at|8)',
        'nigg(a|er)',
        'orgasi?m',
        'porn',
        'pus+[iey]',
        'shit',
        'se(x|c?ks)',
        'shag',
        'slut',
        'ti+t',
        'vagina',
        'viagra',
        'b=+d', // for things like B====D
    ],
};
